services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5555:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
